title: Eric Praniewicz
logo: "/images/Avatar.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Business Intelligence Analyst
  <br><br>
  Industry Experiences include Retail, Real Estate, Design, Construction, Manufacturing
  <br><br>
  <a href="https://www.linkedin.com/in/ericpraniewicz/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-315872232 # your Google Analytics tracking ID here
